version: "3.7"
networks:
  default:
    internal: true
  gateway:
    external:
      name: gateway
volumes:
  blazegraph-data:
services:
  blazegraph:
    restart: ${RESTART_POLICY:-unless-stopped}
    image: ${REPOSITORY:-islandora}/blazegraph:${TAG:-latest}
    volumes:
      - blazegraph-data:/data
    networks:
      default:
    labels:
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME-isle-dc}-blazegraph.loadbalancer.server.port=80
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-blazegraph_http.service=${COMPOSE_PROJECT_NAME-isle-dc}-blazegraph
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-blazegraph_http.entrypoints=blazegraph
