# Container does not perform any initialization aside from importing env-vars from `confd`.
# Users are expected to manually set up their site using a combination of the following:
# - Makefile targets
# - composer requires / install
# - Drush commands
# - Manual changes to the codebase directory
version: "3.7"
networks:
  default:
    internal: true
  gateway:
    name: gateway
volumes:
  drupal-sites-data:
  solr-data:
services:
  drupal:
    build:
      context: .
      args:
        TAG: ${TAG}
        REPOSITORY: ${REPOSITORY}
    image: ${REPOSITORY}/drupal-static:${DRUPAL_STATIC_TAG}
    environment:
      DRUPAL_INSTANCE: static
    volumes:
      - drupal-sites-data:/var/www/drupal/web/sites/default/files
    depends_on:
      # Requires a the very minimum a database.
      - ${DRUPAL_DATABASE_SERVICE}
    secrets:
      - source: saml_secrets
  # Extends docker-compose.solr.yml
  solr:
    volumes:
      # On a production site you may not want to take this approach but instead refer to each of the cores
      # data directories specifically and maintain the configuration as part of a customized image, where
      # in your configuration is Solr managed under source control somewhere.
      - solr-data:/opt/solr/server/solr

secrets:
  saml_secrets:
    file: ./secrets/saml-secrets.yml
